services:
  postgres:
    image: postgres:16-alpine
    container_name: mgroup-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mgroup_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - mgroup_postgres_data:/var/lib/postgresql/data

volumes:
  mgroup_postgres_data:
